PUT http://127.0.0.1:8000/api/event/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiNjJhOGY0YzU2NTJlMzY1ODNmMmE3OTFlYjkzZTkzMDBjYjI0ZDNhM2Y5OGVmODNlNTFmMzVjNTFkZjg4YTdjYWM5OWRhMjliMzA2OWFiNDkiLCJpYXQiOjE1ODA2Mzk1NTMsIm5iZiI6MTU4MDYzOTU1MywiZXhwIjoxNjEyMjYxOTUzLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.bK5RARiSoLhVxzxHSpGKW9rmI7x_SQFkimcGqLyjUYK3P9VuyzI7ix-EncVRyZqkCoXVCTsDtW2tzw2qslKNxjhWzjTYyRVZ6tiNeJ39YlVjIuw4uXuq1OX4HmOhRwHl8S8KSfHC_npAQDelxQ79C-OkuSg41_EoIJg3nT-BuU4LF3eQwBf7HtozKCTrIssUDNGNwysvF4tyrLUN_pnjByQc_V-y5verMQ79PwAddVzMlHlAMiQ3i_u1Y98NN6tuyMh7wUfIwZw0oJ0etf-y5Hq66Vm2VqFp2-HXFYfEHC_YkgWsNgxSjlss4CbbHolaxseY_PIt0nx2kqZx0wNsSZQ3W81Clx1lQ0wxrYwPFIHVIylFHVyO__bJG0BU3dQwfykSkJYxhwtmESf8jIQt5ZHvMLJDIsbXW8iSSs3hpswfHz0HUBDxASRGytRULrdZqnnWfUIXgfIJxMaCB-ns-1PDC09GXL0IA4HGdf1X7DerzQ_qiVp6YJFN4YK0Eg5ssCkvj7RY2DCjdRfwcR7EqcZEMQ6W77JujXdHvPbH3B0TpAzZa3WMAdmteuvyZdO0h0YnwzdyO9fXO0Z8_e70SFGrDNRMXDgmqFBUSRa_kJsrKF89YzMrLe0ZSuFNCYhVqrI3hxwjBoX5s9ZeNkBQo5cfOKFg1kYR8eFj5X0puRE

{   
    "date": "1999-01-14"
}