DELETE http://127.0.0.1:8000/api/event/16
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODI4YjExYWE0ZDM2MjA4YmRmMjdkOTA4NDhhYzIwYjI4NDQwZjE2N2NkMGM1NDIyOWRlOTJiMTA1NWY3NzcxZTBmYTJkODRhM2U5YTRkNzYiLCJpYXQiOjE1ODA2MzY0NTIsIm5iZiI6MTU4MDYzNjQ1MiwiZXhwIjoxNjEyMjU4ODUyLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.M798xqDEnMCwc9Wc26RctMVaiJMEYSnP1KYh-qo3viOCJhxEwh-SE3U9EMiaXUfIdFQQGdUpRw5NoQJmQL-02LEYmiicXbJ1hBKjY5TBX48N5XelKmVNxaG0dpy4DtTiPoXG9nMSKvXHWyqBiylZG4Ro_xL-zU7MkNvyPJnJcI5lNfjH4IhLnE5pdbev1A1kapnFTnSvkZU-FU9toGoXzU2JxSI89pzlIZAjKmJdPu3rVRnUf0ccb0wnkHR3OHOs8mInRVE3Zet6YcUty_csTdh5CX1l12r7bI2XcjCyrYipIKbuxzIr7ikJ9Ero8tsIOSLgQaMkIIRpIx5m7eVpUttc_0oSXweq71JT-te8I4jrD9ldoskvpB5iYA2jHgWIdY8RbSGpc3YWrDdSjxC08RRqtYXcQxEaWyTDEVGQL3pssVExgyA8qN8uulM8zQjIzV9sIq_2EzTbCQ1Jxo7gJLuar6KO427KwHUK4iEh3EL9H5we--ELsRFjy52Uzi80_G7HmhVqL3M9g4FAacvVPUBaiIduRwJvCXqyBYt7Uh9MPvL3N_RUNdBBuFOwB9UFAE559OAdh75SytTomUNw5FpHsHbrLoYW8lDjlUOqQyCuffM-Q-0eD3-GP7m6xFkMAgv8fLdVp2ZsU-fSoeUKkQAHso6Tv5TW5pscfh2XAU4

{
    "date": "1999-03-13"
}